roots = [ "^Main.main$"
 , "^Spec.main$"
 , "^main$"
 , "validatorHash$"
 , "validatorScript$"
 , "queryEpochNo$"
 , "queryUTxOWhole$"
 , "traceDebug$"
 , "spy$"
 , "spy'$"
 , "showFromAction$"
 , "redeemer$"
 ]
root-instances = [ { class = '\.Eq$' }
                 , { class = '\.Show$' }
                 , { class = '\.Read$' }
                 , { class = '\.Enum$' }
                 , { class = '\.Bounded$' }
                 , { class = '\.Generic$' }
                 , { class = '\.Ord$' }
                 , { class = '\.Num$' }
                 , { class = '\.Real$' }
                 , { class = '\.Integral$' }
                 , { module = "Hydra.Contract.Commit", instance = "UnsafeFromData Commit" }
                 , { module = "Hydra.Contract.Commit", instance = "FromData RedeemerType" }
                 , { module = "Hydra.Contract.Commit", instance = "UnsafeFromData RedeemerType" }
                 , { module = "Hydra.Contract.Deposit", instance = "FromData DepositRedeemer" }
                 , { module = "Hydra.Contract.MintAction", instance = "FromData MintAction" }
                 , { module = "Hydra.Network.Ouroboros.Type", instance = "Protocol" }
                 , { module = "Hydra.Chain.Direct.TxTraceSpec", instance = "HasVariables" }
                 , { module = "Hydra.Chain.Direct.TxTraceSpec", instance = "MonadFail AppM" }
                 , { module = "Hydra.Chain.Direct.TxTraceSpec", instance = "MonadThrow AppM" }
                 ]
