# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/github-issue-forms.json
name: 'Feature idea'
description: Idea or request for some feature to add to Hydra
labels: [':thought_balloon: idea']
type: Feature
body:
  - type: markdown
    attributes:
      value: |
        **Thank you for contributing to our project!** :green_heart:

  - type: textarea
    id: feature-description
    attributes:
      label: Description
      description: "Clear and concise description of the problem. Please make the reason and usecases as detailed as possible. If you intend to submit a PR for this issue, tell us in the description. Thanks!"
    validations:
      required: true

  - type: textarea
    id: suggested-solution
    attributes:
      label: Suggested solution
    validations:
      required: true

  - type: textarea
    id: alternative
    attributes:
      label: Alternative
      description: "Clear and concise description of any alternative solutions or features you've considered."

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Any other context or screenshots about the feature request here.
