
name: "Demo test"

on:
  # We're using merge-chains; so this needs to run then.
  merge_group:
  push:
    branches:
      - master
  pull_request:

jobs:
  demo-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Nix/Cachix
        uses: ./.github/actions/nix-cachix-setup
        with:
          authToken: '${{ secrets.CACHIX_CARDANO_SCALING_AUTH_TOKEN }}'

      - name: Check demo test
        run: |
          cd demo
          nix run .#demo -- -D
          sleep 30  # Give time for startup
          cat devnet/alice-logs.txt | grep "APIServerStarted" || exit 1
          nix run .#demo -- down

