name: Check code formatting

on:
  # We're using merge-chains; so this needs to run then.
  merge_group:
  pull_request:

jobs:
  formatting:
    name: Check code formatting
    runs-on: ubuntu-latest
    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v4

    - name: ❄ Prepare nix
      uses: cachix/install-nix-action@v30
      with:
        extra_nix_config: |
          accept-flake-config = true
          log-lines = 1000

    - name: ❄ Cachix cache of nix derivations
      uses: cachix/cachix-action@v15
      with:
        name: cardano-scaling
        authToken: '${{ secrets.CACHIX_CARDANO_SCALING_AUTH_TOKEN }}'

    - name: 📐 Check code formatting
      run: |
        nix build .#checks.x86_64-linux.treefmt

    - name: 📐 Check hlint
      run: |
        nix build .#checks.x86_64-linux.hlint
