name: Nix Flake Check

on:
  merge_group:
  pull_request:

jobs:
  quality:
    name: Nix Flake Check
    runs-on: ubuntu-latest
    steps:
    - name: Reclaim the bytes
      uses: data-intuitive/reclaim-the-bytes@v2
      with:
        # NOTE: Remove more when needed, but these take also time
        # See https://github.com/marketplace/actions/reclaim-the-bytes
        remove-android-sdk: false
        remove-docker-images: false

    - name: 📥 Checkout repository
      uses: actions/checkout@v4

    - name: ❄ Setup Nix/Cachix
      uses: ./.github/actions/nix-cachix-setup
      with:
        authToken: '${{ secrets.CACHIX_CARDANO_SCALING_AUTH_TOKEN }}'

    - name: 📐 Check
      run: |
        nix flake check -L
