name: Check code weeds

on:
  # We're using merge-chains; so this needs to run then.
  merge_group:
  pull_request:

jobs:
  weeder:
    name: Check code weeds
    runs-on: ubuntu-latest
    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v4

    - name: ❄ Setup Nix/Cachix
      uses: ./.github/actions/nix-cachix-setup
      with:
        authToken: '${{ secrets.CACHIX_CARDANO_SCALING_AUTH_TOKEN }}'

    - name: 📐 Check weeder
      run: |
        nix build .#checks.x86_64-linux.weeder
